### ISSUE TITLE
gradle deploy failure

### ISSUE THREAD

**Issue by mozark24** [octopus-platform/bjoern#23]
I followed the installation instructions closely and received the below error during "gradle deploy":

System:
OS:  Debian Jessie
Gradle: 2.6  (Procedure wasn't clear what version of Gradle, so I went with the same as Joern)
OpenJdk: 1.8.0_162

```
:projects:bjoern-plugins:alocs:jarWithDep FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/home/osboxes/Desktop/bjoern/build.gradle' line: 48

* What went wrong:
Execution failed for task ':projects:bjoern-plugins:alocs:jarWithDep'.
> No signature of method: org.gradle.api.internal.file.AbstractFileCollection$1.asCollection() is applicable for argument types: () values: []
```

**Comment by marius-benthin** [comment]
I also get this error during "gradle deploy" on Debian Jessie with Gradle 2.0 and JDK 1.8.0_40.
Is there any solution?

**Comment by mozark24** [comment]
I went to an older version of Linux around when this tool was released and was able to make a bit more progress.

**Comment by s1ckb017** [comment]
System Os: Mac OS Mojave 10.14.2 
Gradle : 2.0
JDK: 1.8.0_202

Same error during: `gradle deploy`

How can I fix this?
Which version of gradle should I use?

StackTrace:
`
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/Desktop/programmi/reverseEngineering/bjoern/bjoern/build.gradle' line: 49

* What went wrong:
Execution failed for task ':projects:bjoern-plugins:alocs:jarWithDep'.
> No signature of method: org.gradle.api.internal.file.AbstractFileCollection$1.asCollection() is applicable for argument types: () values: []

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projects:bjoern-plugins:alocs:jarWithDep'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.file.AbstractFileCollection$1.asCollection() is applicable for argument types: () values: []
	at build_30dlbnf0524tssu9dliv4a20g3$_run_closure6_closure9_closure11.doCall(/Users/user/Desktop/programmi/reverseEngineering/bjoern/bjoern/build.gradle:49)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:520)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 44 more

`

**Comment by s1ckb017** [comment]
System Os: Mac OS Mojave 10.14.2
Gradle : 2.0
JDK: 1.8.0_202

Same error during: `gradle deploy`

How can I fix this?
Which version of gradle should I use?

StackTrace:
```
FAILURE: Build failed with an exception.

* Where:
  Build file '/Users/user/Desktop/programmi/reverseEngineering/bjoern/bjoern/build.gradle' line: 49
* What went wrong:
  Execution failed for task ':projects:bjoern-plugins:alocs:jarWithDep'.

> No signature of method: org.gradle.api.internal.file.AbstractFileCollection$1.asCollection() is applicable for argument types: () values: []

* Try:
  Run with --info or --debug option to get more log output.
* Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projects:bjoern-plugins:alocs:jarWithDep'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:296)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:86)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:67)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:61)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:54)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:148)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:105)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:85)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:81)
  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:39)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:50)
  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
  at org.gradle.launcher.Main.doAction(Main.java:33)
  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.file.AbstractFileCollection$1.asCollection() is applicable for argument types: () values: []
  at build_30dlbnf0524tssu9dliv4a20g3$_run_closure6_closure9_closure11.doCall(/Users/user/Desktop/programmi/reverseEngineering/bjoern/bjoern/build.gradle:49)
  at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
  at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:520)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
  ... 44 more
```

**Comment by Rex0r519** [comment]
@s1ckb017 I suggest mimic'ing the original dev environment as closely as possible (down to the OS).  I was eventually able to get it to work but it took many tries.

**Comment by mozark24** [comment]
@s1ckb017 I suggest mimic'ing the original dev environment as closely as possible (down to the OS). I was eventually able to get it to work but it took many tries.

**Comment by s1ckb017** [comment]
@mozark24 could you suggest me in which configuration bjoern work properly?
I've a MacBook Pro so I don't want downgrade my Os.

**Comment by mozark24** [comment]
Unfortunately, the VM I had it working on I got rid of long ago when I moved on from this project.  If you're not using a VM for this build, you're going to have a bad time.

**Comment by mwy123456** [comment]
System Os: Ubuntu16.04
Gradle : 2.10
JDK: 1.8.0_221

Same error during: gradle deploy

How can I fix this?
Which version of gradle should I use?

StackTrace:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':projects:octopus:octopus-server:compile'.
> Could not download json.jar (org.json:json:20141113)
   > Could not get resource 'https://repo1.maven.org/maven2/org/json/json/20141113/json-20141113.jar'.
      > Could not GET 'https://repo1.maven.org/maven2/org/json/json/20141113/json-20141113.jar'.
         > Connection refused (Connection refused)
